version: '3.8'
services:
  database:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:3306"
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    container_name: php_my_admin
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      database:
        condition: service_healthy

  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: on-failure
    ports:
      - '${SERVER_PORT}:3000'
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "
          ls;
          npm install -g nodemon mysql ts-node;
          npx prisma migrate dev --name banco_total_teste;
          npx prisma generate;
          npm run start;
      "
    volumes:
      - .:/home/node/ts/app
